[4.0] change max-retained-history-files default
AntelopeIO/leap pull request #1141
Opened 2023-05-08 13:52 UTC by huangminghuang

This PR 
- changes the defaults of `max-retained-history-files` to UINT32_MAX when `state-history-retained-dir` is specified,
- adds some unit tests to validate `max-retained-history-files` and `max-retained-block-files`.

Resolves https://github.com/AntelopeIO/leap/issues/1135

2023-05-08 20:50 UTC, linh2931 requested changes

2023-05-08 20:50 UTC, linh2931 commented on libraries/state_history/include/eosio/state_history/log.hpp
> +      uint32_t max_retained_files = UINT32_MAX;
The PR title and description say "change state-history-stride default", but here max_retained_files default is changed. Please correct the PR title and description.

You can add some explanation of this default to the command line help `max-retained-history-files`.

2023-05-08 22:38 UTC, heifner requested changes

2023-05-08 22:38 UTC, heifner commented on plugins/chain_plugin/chain_plugin.cpp
> +const controller::config* chain_plugin::chain_config() const {
I think this should return a `const controller::config&` and `EOS_ASSERT` if null.

2023-05-08 22:38 UTC, heifner commented on plugins/state_history_plugin/state_history_plugin.cpp
> +const state_history_log_config* state_history_plugin::trace_log_config() const {
I think this should be removed. Just use `get_trace_log()` and then if not null `->config()`.

2023-05-09 13:58 UTC, heifner commented on plugins/state_history_plugin/include/eosio/state_history_plugin/state_history_plugin.hpp
> +   const state_history_log* trace_log() const;
Seems odd to provide access to the `trace_log` but not the `chain_state_log`.

2023-05-11 12:39 UTC, heifner approved these changes

2023-05-11 14:19 UTC, linh2931 approved these changes

2023-05-11 17:51 UTC, merged