Infrastructure for hs message filtering
AntelopeIO/leap pull request #1613
Opened 2023-09-09 01:22 UTC by fcecin

- connection ID of hs message sender (net plugin -> IF engine)
- connection ID to exclude when propagating (IF engine -> net plugin)
- added callback to warn of bad HS messages from a connection (IF engine -> net plugin)
- added sample use of the warning callback for discarded proposals and votes
- helpers on qc_chain to allow for easy message propagation (no propagation decisions added)
- no-ops for this feature added to test_pacemaker (which does not have multi-hop)

Closes #1605

Obsoletes PR #1583, which can be closed as message propagation strategy will be decided and then implemented on top of the code in this PR (suggestion https://github.com/AntelopeIO/leap/pull/1583/files/e1cc627a75853e2929df25cbcc3ee4f76066ba37#r1316210590 can be implemented when we remove the qc_chain profiler).

2023-09-11 12:36 UTC, heifner commented on libraries/chain/include/eosio/chain/hotstuff.hpp
> +   enum hs_message_warning : uint32_t {
Make an `enum class`.

2023-09-11 12:53 UTC, heifner requested changes

2023-09-11 12:53 UTC, heifner commented on libraries/hotstuff/include/eosio/hotstuff/qc_chain.hpp
> +      void process_new_block(const hs_new_block_message& msg, bool is_loopback = false); //handles new block
I would prefer to be explicit and not have the default `= false`

2023-09-11 12:53 UTC, heifner commented on libraries/hotstuff/include/eosio/hotstuff/qc_chain.hpp
> +      void send_hs_new_block_msg(const hs_new_block_message& msg, bool propagation = false); //send new block msg
I would prefer to be explicit and not have the default `= false`.
Also a couple of the comments are wrong and they are all completely useless as they do not tell you anything more than the method name.

2023-09-11 12:53 UTC, heifner commented on libraries/hotstuff/include/eosio/hotstuff/qc_chain.hpp
> +      void send_hs_message_warning(const chain::hs_message_warning code = hs_message_warning::discarded); //use generic discard reason if none given
Remove default `= hs_message_warning::discarded`. Should be explicit about it.

2023-09-11 12:53 UTC, heifner commented on libraries/hotstuff/qc_chain.cpp
> +      _sender_connection_id = std::nullopt;
Storing the sender connection id seems like an anti-pattern to me. It provides a point of contention between the threads interacting with `qc_chain`. I know this is all protected by a large mutex, but if we want to remove that in the future seems much cleaner to pass along connection id via the call stack.

2023-09-11 15:17 UTC, linh2931 commented on libraries/hotstuff/chain_pacemaker.cpp
> +      std::lock_guard g( _hotstuff_global_mutex ); // not actually needed but doesn't hurt
If it is not needed, remove it; but leave a comment explaining it is not required.

2023-09-11 18:09 UTC, heifner approved these changes

2023-09-11 18:57 UTC, linh2931 approved these changes

2023-09-11 19:51 UTC, merged

2023-10-13 17:19 UTC, ericpassmore commented
Note:start
group: IF
category: MESSAGES
summary: Filters hotstuff messages by accepting an optional list of peers to exclude from sending messages.
Note:end