Add a couple boost deps to add_eosio_test_executable macro
AntelopeIO/leap pull request #1638
Opened 2023-09-14 17:52 UTC by oschwaldp-oci

These dependencies allow for additional use of add_eosio_test_executable outside of leap for executables loosely defined as test artifacts.  For example, compiling a transaction generator in another repository.

2023-09-14 18:07 UTC, heifner approved these changes

2023-09-14 18:31 UTC, spoonincode requested changes
How difficult would it be to refactor this cmake file to present maybe a `add_library(libtester STATIC IMPORTED)`. Then the existing `add_eosio_test_executable` would just link to the `IMPORTED libtester`, but when you're not making a test executable you would just `target_link_libraries(whatever libtester)`

Adding dependencies like this makes it difficult to know the union of all downstream dependencies when reviewing this file in the future.

2023-09-15 17:07 UTC, oschwaldp-oci commented
> How difficult would it be to refactor this cmake file to present maybe a `add_library(libtester STATIC IMPORTED)`. Then the existing `add_eosio_test_executable` would just link to the `IMPORTED libtester`, but when you're not making a test executable you would just `target_link_libraries(whatever libtester)`
> 
> Adding dependencies like this makes it difficult to know the union of all downstream dependencies when reviewing this file in the future.

@spoonincode -- How about going the direction of an `INTERFACE` library like you had also mentioned out of band earlier?  Proposal: [3e22bd1](https://github.com/AntelopeIO/leap/pull/1638/commits/3e22bd19882d61db43ed6e2c089526941c529f63)

2023-09-15 17:10 UTC, spoonincode commented
Yes true, `INTERFACE` is considerably easier than `IMPORTED` in this case since we have a handful of static libraries.

2023-09-18 14:30 UTC, spoonincode approved these changes

2023-09-18 14:34 UTC, merged