IF: Add a new set_finalizer (with weights, threshold, and local finalizer) to libtester and add more tests using it
AntelopeIO/leap pull request #2208
Opened 2024-02-05 18:55 UTC by linh2931

* Add a new set_finalizer which takes  threshold, weight and local finalizers as arguments
* Using the new function, add tests `threshold_equal_to_half_weight_sum_test`, `votes_equal_to_threshold_test`, `votes_greater_than_threshold_test`, and `votes_less_than_threshold_test`.

Resolved https://github.com/AntelopeIO/leap/issues/2193

2024-02-05 22:42 UTC, heifner requested changes

2024-02-05 22:42 UTC, heifner commented on unittests/api_tests.cpp
> +void test_finality_transition(const vector<account_name> accounts, const base_tester::finalizer_policy_input& input, bool lib_advancing_expected) {
Can be `const&`

2024-02-05 23:20 UTC, greg7mdp approved these changes

2024-02-05 23:20 UTC, greg7mdp commented on unittests/api_tests.cpp
> +   base_tester::finalizer_policy_input ploicy_input = {
type in all the `ploicy_input`.

2024-02-05 23:20 UTC, greg7mdp commented on libraries/testing/include/eosio/testing/tester.hpp
> +         transaction_trace_ptr  set_finalizers(const vector<account_name>& finalier_names);
typo in `finalier_names`

2024-02-05 23:57 UTC, linh2931 commented on libraries/testing/tester.cpp
> +   transaction_trace_ptr base_tester::set_finalizers(const finalizer_policy_input& input ) {
Thanks. I will make the change.

2024-02-05 23:58 UTC, linh2931 commented on libraries/testing/include/eosio/testing/tester.hpp
> +         transaction_trace_ptr  set_finalizers(const vector<account_name>& finalier_names);
Thanks!

2024-02-05 23:58 UTC, linh2931 commented on unittests/api_tests.cpp
> +   base_tester::finalizer_policy_input ploicy_input = {
Will correct them.

2024-02-06 01:33 UTC, heifner approved these changes

2024-02-06 03:18 UTC, merged

2024-02-06 16:43 UTC, ericpassmore commented
Note:start
group: IF
category: INTERNALS
summary: Updated set finalizer which takes threshold, weight and local finalizers as arguments.
Note:end

2024-10-02 13:48 UTC, ericpassmore commented
Note:start
category: Tests
component: Internal
summary: Updated set finalizer which takes threshold, weight and local finalizers as arguments.
Note:end