IF: Sign and verify signature or proposed blocks
AntelopeIO/leap pull request #2241
Opened 2024-02-18 03:32 UTC by heifner

Sign `block_id` of proposed blocks and verify signatures on validation nodes.

- Also adds validation of activated protocol features.
- Includes a test that protocol feature activation works after instant_finality is enabled.
- Existing tests cover block signing validation. Many tests failed when I signed with the wrong producer key.

Resolves #2142

2024-02-18 16:23 UTC, greg7mdp approved these changes
Looks great, nice test for protocol feature activation under savanna.

2024-02-18 19:57 UTC, linh2931 requested changes
Maybe later add a test for rejecting unsigned blocks?

2024-02-18 19:57 UTC, linh2931 commented on libraries/chain/block_state.cpp
> +              "block signed by unexpected key",
Missing `${signing_keys)` and `${authority}`. You can also log `relevant_sig_count`

2024-02-18 19:57 UTC, linh2931 commented on libraries/chain/block_state.cpp
> +              "block signatures do not satisfy the block signing authority",
The same missing `${signing_keys)` and `${authority}`

2024-02-18 19:57 UTC, linh2931 commented on libraries/chain/block_state.cpp
> +      EOS_ASSERT(res.second, wrong_signing_key, "block signed by same key twice", ("key", *res.first));
Missing ${key}

2024-02-18 19:57 UTC, linh2931 commented on libraries/chain/block_state.cpp
> +   block->producer_signature = sigs.back();
Maybe add a comment here saying the last is producer_signature and the rest is additional_signatures.

2024-02-19 14:01 UTC, linh2931 approved these changes

2024-02-19 14:10 UTC, greg7mdp approved these changes

2024-02-19 14:58 UTC, merged

2024-02-19 19:35 UTC, ericpassmore commented
Note:start
group: IF
category: INTERNALS
summary: Sign block_id of proposed blocks and verify signatures on validation nodes.
Note:end