[3.2] Dropped trxs when overloaded logged as warning in nodeos
AntelopeIO/leap pull request #355
Opened 2022-10-19 20:19 UTC by ClaytonCalabrese

Currently when a transaction is rejected due to too many transactions in progress, that message only gets logged in a "debug" logging level. Rather than spamming that message at a higher level, instead add a new message which will periodically be printed as long as transactions are being rejected.

In this implementation that is the first time a transaction is rejected due to too many transactions, and every time it happens at an interval of 1 second or more.

Resolves: https://github.com/AntelopeIO/leap/issues/351

2022-10-19 20:37 UTC, heifner requested changes

2022-10-19 20:37 UTC, heifner commented on plugins/net_plugin/net_plugin.cpp
> +      fc::time_point                   last_dropped_trx_msg_time;
This section of variables are protected by `conn_mtx`, see comment on line 652. I would move it up under `trx_in_progress_size`. It is only accessed via the connection strand, so no mutex is needed.

2022-10-19 20:37 UTC, heifner commented on plugins/net_plugin/net_plugin.cpp
> +            wlog("Speculative execution is REJECTING transactions, too many trx in progress");
Remove "Speculative execution is" as this is not necessarily speculative execution. Also, go ahead and log the `trx_in_progress_sz`. For that matter, might as well just `wlog(reason);`

2022-10-19 20:38 UTC, heifner commented
Should target this to 3.1.

2022-10-19 23:03 UTC, matthewdarwin commented
I hope all these failures are well explained with `transaction_failure_tracing` set to debug?

2022-10-20 14:41 UTC, heifner commented
> I hope all these failures are well explained with `transaction_failure_tracing` set to debug?

Yes they are included in that log, in the form:
`[TRX_TRACE] Speculative execution is REJECTING tx: ${txid} : Dropping trx, too many trx in progress %lu bytes`

2022-10-25 20:44 UTC, closed without merging