Prometheus Tracking Pull Request
AntelopeIO/leap pull request #623
Opened 2023-01-06 17:38 UTC by ndcgundlach

This is a pull request to track diffs between feature_prometheus_plugin and main.  When it is ready to merge into main, it will be moved out of draft status.

2023-02-22 15:41 UTC, heifner requested changes
Please update the PR description with a summary of all the prometheus tracked values.

2023-02-22 15:41 UTC, heifner commented on plugins/net_plugin/include/eosio/net_plugin/net_plugin.hpp
> +      runtime_metric num_peers{metric_type::gauge, "num_peers", "num_peers", 0};
Is it useful to have `label` and `family` the same? What if you just leave one as `""` does that cause a problem?

2023-02-22 15:41 UTC, heifner commented on plugins/prometheus_plugin/include/eosio/prometheus_plugin/prometheus_plugin.hpp
> +      std::string metrics();
This can be removed, it is not used.

2023-02-22 15:41 UTC, heifner commented on plugins/prometheus_plugin/prometheus_plugin.cpp
> +         auto &counter = counter_family.Add({});
`auto& `

2023-02-22 15:41 UTC, heifner commented on plugins/prometheus_plugin/prometheus_plugin.cpp
> +         eosio::chain::named_thread_pool<prom> _prometheus_thread_pool;
`eosio::chain::named_thread_pool<struct prom> _prometheus_thread_pool;`
Then you don't need the external `struct prom;` above.

2023-02-22 15:41 UTC, heifner commented on plugins/prometheus_plugin/prometheus_plugin.cpp
> +      struct prometheus_plugin_impl {
Fix indentation.

2023-02-22 15:41 UTC, heifner commented on plugins/prometheus_plugin/prometheus_plugin.cpp
> +         void update_metrics(std::string plugin_name, vector<runtime_metric> metrics) {
`const std::string& plugin_name`

2023-02-22 15:41 UTC, heifner commented on plugins/prometheus_plugin/prometheus_plugin.cpp
> +         metrics_listener create_metrics_listener(std::string plugin_name) {
Could take string as a const& or std::move it into lambda

2023-02-22 15:41 UTC, heifner commented on plugins/prometheus_plugin/prometheus_plugin.cpp
> +            auto start_time_of_request = std::chrono::steady_clock::now();
Not used.

2023-02-22 15:41 UTC, heifner commented on plugins/prometheus_plugin/prometheus_plugin.cpp
> +            auto stop_time_of_request = std::chrono::steady_clock::now();
Not used.

2023-02-22 15:41 UTC, heifner commented on plugins/prometheus_plugin/prometheus_plugin.cpp
> +      prometheus_api(prometheus_plugin_impl& plugin) : _pp(plugin){
`explicit`

2023-02-22 15:41 UTC, heifner commented on plugins/prometheus_plugin/prometheus_plugin.cpp
> +      fc::microseconds max_response_time_us{30*1000};
Should use the max response time of http_plugin

2023-02-22 15:41 UTC, heifner commented on plugins/prometheus_plugin/prometheus_plugin.cpp
> +   prometheus_plugin::~prometheus_plugin() {}
`= default;`

2023-02-22 15:41 UTC, heifner commented on plugins/prometheus_plugin/prometheus_plugin.cpp
> +      my->_prometheus_thread_pool.start(1, []( const fc::exception& e ) {} );
Log the exception. In this particular case we likely do not want to `app().quit()`, but open to other opinions.

2023-02-22 15:41 UTC, heifner commented on unittests/CMakeLists.txt
> +                            ${CMAKE_SOURCE_DIR}/plugins/chain_interface/include)
Not part of your work, but `unittests/plugin_tests.cpp` should be moved to `tests` so these are not needed. I added a comment here: https://github.com/AntelopeIO/leap/issues/586#issuecomment-1440273072

2023-02-22 15:43 UTC, heifner commented
I believe you have it on your list of todos, but we need an integration test for this plugin.

2023-02-28 14:14 UTC, heifner commented on plugins/chain_interface/include/eosio/chain/plugin_interface.hpp
> +      fc::microseconds _min_post_interval_ms;
`ms` is abbreviation for milliseconds not microseconds `us`

2023-02-28 14:16 UTC, heifner commented on plugins/chain_interface/include/eosio/chain/plugin_interface.hpp
> +      explicit plugin_metrics(fc::microseconds min_post_interval_ms=fc::microseconds(250)) : _min_post_interval_ms(min_post_interval_ms), _listener(nullptr) {}
`fc::microseconds min_post_interval_us=fc::milliseconds(250)`

2023-02-28 14:18 UTC, heifner commented on plugins/chain_interface/include/eosio/chain/plugin_interface.hpp
> +         return ((_listener) && fc::time_point::now() > (_last_post + fc::milliseconds(_min_post_interval_ms.count()*1000)));
```suggestion
         return ((_listener) && fc::time_point::now() > (_last_post + _min_post_interval_us);
```

2023-03-08 20:27 UTC, linh2931 approved these changes

2023-03-09 02:47 UTC, heifner commented on plugins/chain_interface/include/eosio/chain/plugin_interface.hpp
> +   //
Moved to `plugin_metrics.hpp`

2023-03-09 02:47 UTC, heifner commented on plugins/http_plugin/http_plugin.cpp
> +
Removed

2023-03-09 02:47 UTC, heifner commented on plugins/http_plugin/http_plugin.cpp
>            * @param my - the http_plugin_impl
Added.

2023-03-09 02:50 UTC, heifner commented on plugins/prometheus_plugin/prometheus_plugin.cpp
> +        return std::vector{
Fixed.

2023-03-09 02:53 UTC, heifner commented on plugins/prometheus_plugin/prometheus_plugin.cpp
> +      void add_runtime_metrics(std::vector<runtime_metric>& metrics){
Added.

2023-03-09 02:54 UTC, heifner commented on plugins/prometheus_plugin/prometheus_plugin.cpp
> +            dlog("net_plugin not found -- metrics not added");
Made a warning.

2023-03-09 02:54 UTC, heifner commented on plugins/prometheus_plugin/prometheus_plugin.cpp
> +            dlog("producer_plugin not found -- metrics not added");
Fixed.

2023-03-09 03:00 UTC, heifner commented on plugins/prometheus_plugin/prometheus_plugin.cpp
> +      my->_prometheus_thread_pool.stop();
Other plugins are posting into this thread pool from other threads that could still be running. Those capture `this` so it is safter to `stop()` it before destroying `my`.

2023-03-09 03:06 UTC, heifner commented on plugins/prometheus_plugin/prometheus_plugin.cpp
> +         ilog("Added gauge metric ${f}:${l}", ("f", plugin_metric.family) ("l", plugin_metric.label));
Made it a tlog

2023-03-10 18:34 UTC, linh2931 reviewed
It would be nice to have an instruction (or future document) on how to connect to nodeos to retrieve those metrics.

It is also nice to have an end-to-end test to do that.

2023-03-13 18:00 UTC, heifner commented
> It would be nice to have an instruction (or future document) on how to connect to nodeos to retrieve those metrics.
> 
> It is also nice to have an end-to-end test to do that.

Integration test added.

2023-03-13 18:57 UTC, heifner approved these changes

2023-03-13 18:57 UTC, merged