subjective-account-max-failures-window-size
AntelopeIO/leap pull request #777
Opened 2023-03-03 20:18 UTC by huangminghuang

This PR adds a new configuration option `--subjective-account-max-failures-window-size` to set the window size in number of blocks for `--subjective-account-max-failures`  option.

2023-03-04 19:34 UTC, heifner requested changes

2023-03-04 19:34 UTC, heifner commented on plugins/producer_plugin/producer_plugin.cpp
> +                                 _account_fails.next_reset_timepoint(chain.head_block_num(), bt))))));
Please cleanup this formatting.

2023-03-04 19:34 UTC, heifner commented on plugins/producer_plugin/producer_plugin.cpp
> +                              _account_fails.next_reset_timepoint(chain.head_block_num(), chain.head_block_time())))));
Please cleanup this formatting.

2023-03-04 19:34 UTC, heifner commented on plugins/producer_plugin/producer_plugin.cpp
> +   _account_fails.report(new_bs->block_num);
I think you should make it `report_and_clear(uint32_t block_num)` and only call it from start_block. The `-1` in `report` vs `clear` seems a bit fragile.

2023-03-06 15:35 UTC, heifner approved these changes

2023-03-06 16:56 UTC, heifner commented
> Just curious, why do we do the `++` here?
> 
> https://github.com/AntelopeIO/leap/blob/71548a642577e0757f0e462bdaba20afa4f3841e/plugins/producer_plugin/producer_plugin.cpp#L223

Because we log the number of failures and want to include this failure in that number.

2023-03-06 17:00 UTC, greg7mdp commented
> Because we log the number of failures and want to include this failure in that number.

But there is an add() function above. It seems that we should have an add() function incrementing the number of failures, and a `failure_limit` to only check if the limit was exceeded?

2023-03-06 17:28 UTC, heifner commented
> > Because we log the number of failures and want to include this failure in that number.
> 
> But there is an add() function above. It seems that we should have an add() function incrementing the number of failures, and a `failure_limit` to only check if the limit was exceeded?

We don't want to add(), only increase the failure count.

2023-03-06 21:20 UTC, greg7mdp approved these changes

2023-03-07 14:19 UTC, merged