Merge PR #777 to release/3.2
AntelopeIO/leap pull request #785
Opened 2023-03-07 15:27 UTC by huangminghuang

This PR merges PR #777 into release/3.2 branch with the following changes

- adds a new configuration option --subjective-account-max-failures-window-size to set the window size in number of blocks for --subjective-account-max-failures option.
- extract the block tracking functionality from `account_failures` class into a `block_time_tracker` class.

2023-03-07 16:06 UTC, greg7mdp approved these changes

2023-03-08 03:31 UTC, heifner requested changes
A similar fix as indicated in this review is needed in 3.1.

2023-03-08 03:31 UTC, heifner commented on plugins/producer_plugin/producer_plugin.cpp
> +            _time_tracker.report_and_clear( _idle_trx_time );
It is ok to clear here, but not needed. So I think we can separate `report()` from `clear()` for `time_tracker`.

2023-03-08 16:15 UTC, heifner approved these changes

2023-03-08 16:45 UTC, merged

2023-03-09 16:28 UTC, heifner commented
> A similar fix as indicated in this review is needed in 3.1.

3.1 does not have reporting of block info like 3.2, no change is needed in 3.1.