[4.0] Change from 500 to 400 http error code for exceptions during http processing
AntelopeIO/leap pull request #903
Opened 2023-03-27 13:46 UTC by heifner

FC and STD Exceptions during http processing is almost always because a resource can't be found. Modify reporting of exceptions from current `500` to `400`. An exception doesn't normally mean there is something wrong with `nodeos`.

See https://moz.com/learn/seo/http-status-codes
4xxs – Client errors: Page not found. The site or page couldn’t be reached. (The request was made, but the page isn’t valid — this is an error on the website’s side of the conversation and often appears when a page doesn’t exist on the site.)

HTTP Status Code 500 - Internal Server Error
Instead of the problem being with pages missing or not found, this status code indicates a problem with the server. A 500 is a classic server error and will affect access to your site. Human visitors and bots alike will be lost, and your link equity will go nowhere fast. Search engines prefer sites that are well maintained, so you’ll want to investigate these status codes and get these fixed as soon as you encounter them.

2023-03-27 13:56 UTC, linh2931 approved these changes

2023-03-27 14:33 UTC, spoonincode requested changes
This is changing behavior that has existed since 1.0. It's something we've always discussed changing, but why now in the middle of a RC?

2023-03-27 16:19 UTC, spoonincode commented
This seems to be a really broad change to the API, if I'm understanding right. For `read_only::get_account()` you added
https://github.com/AntelopeIO/leap/blob/32daed0840801e6a72b55159b732e03f42dc83d8/plugins/chain_plugin/chain_plugin.cpp#L2545
but then changed _any_ `fc::exception` or `std::exception` (besides `unknown_block_exception`, `invalid_http_request`, `unsatisfied_authorization`, `tx_duplicate`, or `eof_exception`) to be 400 instead of 500
https://github.com/AntelopeIO/leap/blob/32daed0840801e6a72b55159b732e03f42dc83d8/plugins/http_plugin/http_plugin.cpp#L405-L415
How come `account_query_exception` wasn't specialized as a 400 or 404 above instead? Wouldn't that isolate the 500->400 change to just account lookup, making the fallout from this change a little more predictable?

2023-03-28 12:52 UTC, heifner commented
Reworked via https://github.com/AntelopeIO/leap/pull/912

2023-03-28 12:52 UTC, closed without merging