[4.0] Clean tmp and TestLogs after test runs
AntelopeIO/leap pull request #915
Opened 2023-03-28 21:01 UTC by ClaytonCalabrese

This PR cleans up a number of tests that have been littering.

`unittests/snapshot_tests.cpp` was leaving tmp files around even on success

These tests were all leaving logs around in TestLogs even on on success:
`tests/auto_bp_peering_test.py`
`tests/cli_test.py`
`tests/nodeos_contrl_c_test.py`
`tests/plugin_http_api_test.py`
`tests/trace_plugin_test.py`
`test/performance_test_basic` (nonbasic also as a result)

`unittests/restart_chain_tests.cpp` had some old code that was unused, which had previously behaved similarly to temp_dir.

Additionally changed `tests/TestHarness/WalletMgr.py` to clean up the test wallets after test success.

Resolves: https://github.com/AntelopeIO/leap/issues/719

2023-03-29 16:38 UTC, heifner approved these changes

2023-03-29 18:18 UTC, oschwaldp-oci requested changes

2023-03-29 18:18 UTC, oschwaldp-oci commented on tests/TestHarness/WalletMgr.py
> +            os.remove(WalletMgr.__walletLogErrFile)
Could we push these 2 files into the `__walletDataDir`?

2023-03-29 20:43 UTC, oschwaldp-oci approved these changes

2023-03-31 18:59 UTC, ScottBailey approved these changes

2023-03-31 19:13 UTC, merged