[4.0] Added missing calls to wasmifs on read-only threads
AntelopeIO/leap pull request #964
Opened 2023-04-04 18:57 UTC by linh2931

Resolve https://github.com/AntelopeIO/leap/issues/963

- Added missing calls to wasmifs on read-only threads
- Removed first_block_num_used from wasm_instantiation_cache.emplace
- Removed thread_local for wasmifs

2023-04-04 21:43 UTC, linh2931 commented on libraries/chain/webassembly/cf_system.cpp
> +      context.control.wasm_interface_exit();
Thanks Matt. You are correct. I was wrong to exit other executing contracts. Am reverting it.

2023-04-04 21:49 UTC, linh2931 commented on libraries/chain/webassembly/cf_system.cpp
> +      context.control.wasm_interface_exit();
I am looking into https://github.com/AntelopeIO/leap/issues/956 after this PR.

2023-04-05 16:33 UTC, heifner commented
This `static` map causes instability:
https://github.com/AntelopeIO/leap/blob/9a10c803b3a49fd08213ddea11f1d6552a037e9f/libraries/wasm-jit/Source/IR/Types.cpp#L20

Here is how I fixed it:
```
diff --git a/libraries/wasm-jit/Source/IR/Types.cpp b/libraries/wasm-jit/Source/IR/Types.cpp
index d1ade9c3b1..ff3704fd67 100644
--- a/libraries/wasm-jit/Source/IR/Types.cpp
+++ b/libraries/wasm-jit/Source/IR/Types.cpp
@@ -1,6 +1,7 @@
 #include "Types.h"

 #include <map>
+#include <mutex>

 namespace IR
 {
@@ -25,6 +26,8 @@ namespace IR
        template<typename Key,typename Value,typename CreateValueThunk>
        Value findExistingOrCreateNew(std::map<Key,Value>& map,Key&& key,CreateValueThunk createValueThunk)
        {
+      static std::mutex mtx;
+      std::lock_guard<std::mutex> g(mtx);
                auto mapIt = map.find(key);
                if(mapIt != map.end()) { return mapIt->second; }
                else
```
There is tabs in that file, so the indentation looks weird in the diff.

2023-04-05 16:34 UTC, heifner requested changes
Fix use of static map

2023-04-05 17:05 UTC, spoonincode commented
@heifner that maybe should be another issue; though it wouldn't surprise me if it's related to #969 since what is pointed to in there may be the root cause of WAVM code being touched from multiple threads.

2023-04-05 17:25 UTC, heifner approved these changes
Approved assuming that the `static map` will be fixed in a diff PR.

2023-04-05 17:33 UTC, linh2931 commented
I am doing a separate PR for https://github.com/AntelopeIO/leap/issues/969 shortly.

2023-04-05 18:53 UTC, linh2931 commented
The PR is https://github.com/AntelopeIO/leap/pull/975

2023-04-05 19:41 UTC, heifner commented
> This `static` map causes instability:

Verified that https://github.com/AntelopeIO/leap/pull/975 fixes this issue.

2023-04-05 20:12 UTC, linh2931 commented
Thanks @heifner and @spoonincode!

2023-04-05 20:20 UTC, spoonincode approved these changes
Looks good

2023-04-05 20:20 UTC, spoonincode commented on libraries/chain/controller.cpp
> +   std::unordered_map<std::thread::id, std::unique_ptr<wasm_interface>> threaded_wasmifs; // one for each read-only thread, used by eos-vm and eos-vm-jit
I'm not sure you need a `unique_ptr` here.. couldn't you just `emplace()` the `wasm_interface` in?

2023-04-05 22:37 UTC, merged